import tseslint from "typescript-eslint";
import jsdoc from "eslint-plugin-jsdoc";
import importPlugin from "eslint-plugin-import";
import preferArrow from "eslint-plugin-prefer-arrow";
import prettierConfig from "eslint-config-prettier";

export default tseslint.config(
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
        sourceType: "module",
      },
    },
  },
  {
    plugins: {
      jsdoc,
      import: importPlugin,
      "prefer-arrow": preferArrow,
    },
  },
  {
    rules: {
      // TypeScript ESLint rules (from original .eslintrc.js)
      "@typescript-eslint/adjacent-overload-signatures": "warn",
      "@typescript-eslint/array-type": ["warn", { default: "array" }],
      "@typescript-eslint/consistent-type-assertions": "off",
      "@typescript-eslint/dot-notation": "off",
      "@typescript-eslint/explicit-member-accessibility": "off",
      "@typescript-eslint/member-ordering": "off",
      "@typescript-eslint/naming-convention": "off",
      "@typescript-eslint/no-empty-function": "warn",
      "@typescript-eslint/no-empty-interface": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-misused-new": "warn",
      "@typescript-eslint/no-namespace": "warn",
      "@typescript-eslint/no-parameter-properties": "off",
      "@typescript-eslint/no-shadow": "off",
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-unused-expressions": "warn",
      "@typescript-eslint/no-unused-vars": "warn",
      "@typescript-eslint/no-use-before-define": "off",
      "@typescript-eslint/no-var-requires": "warn",
      "@typescript-eslint/prefer-for-of": "off",
      "@typescript-eslint/prefer-function-type": "warn",
      "@typescript-eslint/prefer-namespace-keyword": "warn",
      "@typescript-eslint/prefer-rest-params": "off",
      "@typescript-eslint/quotes": "off",
      "@typescript-eslint/triple-slash-reference": ["warn", { path: "always", types: "prefer-import", lib: "always" }],
      "@typescript-eslint/type-annotation-spacing": "off",
      "@typescript-eslint/unified-signatures": "warn",

      // General rules (from original .eslintrc.js)
      "brace-style": "off",
      "comma-dangle": "off",
      "complexity": "off",
      "constructor-super": "warn",
      "curly": "off",
      "dot-notation": "off",
      "eol-last": "off",
      "eqeqeq": ["warn", "smart"],
      "guard-for-in": "off",
      "id-denylist": ["warn", "any", "Number", "number", "String", "string", "Boolean", "boolean", "Undefined", "undefined"],
      "id-match": "warn",
      "import/order": "off",
      "jsdoc/check-alignment": "warn",
      "jsdoc/check-indentation": "warn",
      "max-classes-per-file": "off",
      "new-parens": "warn",
      "no-bitwise": "warn",
      "no-caller": "warn",
      "no-cond-assign": "warn",
      "no-console": "off",
      "no-debugger": "warn",
      "no-empty": "warn",
      "no-empty-function": "warn",
      "no-eval": "warn",
      "no-fallthrough": "off",
      "no-invalid-this": "off",
      "no-multiple-empty-lines": "off",
      "no-new-wrappers": "warn",
      "no-shadow": "off",
      "no-throw-literal": "warn",
      "no-trailing-spaces": "off",
      "no-undef-init": "warn",
      "no-underscore-dangle": "warn",
      "no-unsafe-finally": "warn",
      "no-unused-expressions": "warn",
      "no-unused-labels": "warn",
      "no-use-before-define": "off",
      "no-var": "off",
      "object-shorthand": "off",
      "one-var": ["off", "never"],
      "prefer-arrow/prefer-arrow-functions": "off",
      "prefer-const": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off",
      "quote-props": "off",
      "quotes": "off",
      "radix": "warn",
      "space-before-function-paren": "off",
      "use-isnan": "warn",
      "valid-typeof": "off",
    },
  },
  prettierConfig,
  {
    ignores: ["**/dist/**", "**/node_modules/**", "**/coverage/**", "**/cypress/**"],
  },
);